FilmsCatalog/Components/FilmListViewComponent.cs
using FilmsCatalog.Models;
using FilmsCore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;


namespace FilmListCatalog.Components
{

    public class FilmListViewComponent : ViewComponent
    {
        IFilmsRepository _film;
        public FilmListViewComponent(IFilmsRepository film)
        {
            _film = film;
        }
        public IViewComponentResult Invoke(string find, int page=0)
        {
            Expression<Func<Film, bool>> expr = null;

            if (!string.IsNullOrWhiteSpace(find))
            {
                expr = m =>  m.Name.Contains(find) || m.Description.Contains(find); 
            }
            return View(_film.GetFilmsToTable(expr, 10,page*10));
        }
    }
}

FilmsCatalog/Components/FormFilmViewComponent.cs
using FilmsCore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Components
{
    public class FormFilmViewComponent : ViewComponent
    {
        IFilmsRepository _film;
        public FormFilmViewComponent(IFilmsRepository film)
        {
            _film = film;
        }

        public IViewComponentResult Invoke(int id)
        {


            return View(_film.GetForm(id));
        }
    }
}

FilmsCatalog/Components/PaginationViewComponent.cs
using FilmsCore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Components
{
    public class PaginationViewComponent : ViewComponent
    {
        IFilmsRepository _film;
        public PaginationViewComponent(IFilmsRepository film)
        {
            _film = film;
        }

        public IViewComponentResult Invoke(bool is_searh=true)
        {

            return View();
        }
    }
}

FilmsCatalog/Controllers/FileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Controllers
{
    public class FileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddFile(IFormFile uploadedFile)
        {


            return RedirectToAction("Index");
        }
    }
}

FilmsCatalog/Views/Films/Components/FormFilm/Default.cshtml
@model FilmsCore.Classes.DTOClasses.EditFilm

<form data-ajax='true' id='formFilm' method='post'>

    @Html.Hidden("edit_id", Model.edit_id)
    <div class="form-group">
        <label for="edit_Name">Название</label>
        <input type="text" class="form-control" id="edit_Name" name="edit_Name" placeholder="Название" value="@Model.edit_Name">
    </div>

    <div class="form-group">
        <label for="exampleFormControlTextarea1">Описание фильма</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" name="edit_Description" rows="3">@Model.edit_Description</textarea>
    </div>
    <div class="form-group">
        <label for="edit_year">Год</label>
        <input type="number" class="form-control" id="edit_year" name="edit_year" placeholder="Год" value="@Model.edit_year">
    </div>
    <div class="form-group">
        <label for="edit_produser">Режиссёр</label>
        <input type="text" class="form-control" id="edit_produser" name="edit_produser" placeholder="Режиссёр" value="@Model.edit_produser">
    </div>
    @*<input type="file" name="uploadedFile" accept="image/png, image/gif, image/jpeg" /><br>*@
</form>
<form id="form" name="form" action="/Films/AddFile" enctype="multipart/form-data" method="post">

    <input type="file" name="uploadedFile" id="uploadedFile" accept="image/png, image/gif, image/jpeg" />
</form>
    <br>

    @*<form asp-action="AddFile" asp-controller="File" method="post" enctype="multipart/form-data">
            <input type="submit" value="Загрузить" />
        </form>*@




    <button class="btn btn-primary" onclick='submitfilm()'>Submit</button>