FilmsCatalog/Components/FilmListViewComponent.cs
using FilmsCatalog.Models;
using FilmsCore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;


namespace FilmListCatalog.Components
{

    public class FilmListViewComponent : ViewComponent
    {
        IFilmsRepository _film;
        public FilmListViewComponent(IFilmsRepository film)
        {
            _film = film;
        }
        public IViewComponentResult Invoke(string find, int page=0)
        {
            Expression<Func<Film, bool>> expr = null;

            if (!string.IsNullOrWhiteSpace(find))
            {
                expr = m =>  m.Name.Contains(find) || m.Description.Contains(find); 
            }
            return View(_film.GetFilmsToTable(expr, 10,page*10));
        }
    }
}

FilmsCatalog/Components/FormFilmViewComponent.cs
using FilmsCore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Components
{
    public class FormFilmViewComponent : ViewComponent
    {
        IFilmsRepository _film;
        public FormFilmViewComponent(IFilmsRepository film)
        {
            _film = film;
        }

        public IViewComponentResult Invoke(int id)
        {


            return View(_film.GetForm(id));
        }
    }
}

FilmsCatalog/Components/PaginationViewComponent.cs
using FilmsCore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Components
{
    public class PaginationViewComponent : ViewComponent
    {
        IFilmsRepository _film;
        public PaginationViewComponent(IFilmsRepository film)
        {
            _film = film;
        }

        public IViewComponentResult Invoke(bool is_searh=true)
        {

            return View();
        }
    }
}

FilmsCatalog/Controllers/FilmsController.cs
using FilmsCore.Classes.DTOClasses;
using FilmsCore.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Controllers
{
    public class FilmsController : Controller
    {
        IFilmsRepository _film;
        private IWebHostEnvironment _hostingEnvironment;

        public FilmsController(IFilmsRepository film, IWebHostEnvironment environment)
        {
            _film = film;
            _hostingEnvironment = environment;
        }
        [Authorize]
        public IActionResult List()
        {
            decimal count_pages = (decimal)_film.FilmsCount() / 10;
            ViewBag.CountPages = Math.Ceiling(count_pages);
            return View();
        }

        public IActionResult DebugForm()
        {
            return View();
        }

        [HttpPost]
        public  JsonResult SubmitFilm(EditFilm film)
        {
             
            // если есть лшибки - возвращаем false
            if (!ModelState.IsValid)
                return Json(false);

            try
            {
                return Json(_film.SubmitFilm(film));
            }
            catch
            {
                return Json(-1);
            }
        }
        [HttpPost]
        public IActionResult AddFile( IFormFile file, int id_film)
        {
            Guid file_guid = Guid.NewGuid();
            string fileName = System.IO.Path.GetFileName(file.FileName);
            string ext = System.IO.Path.GetExtension(file.FileName);
            string uploads = Path.Combine(_hostingEnvironment.WebRootPath, "Files");
        
                if (file.Length > 0)
                {

                    string filePath = Path.Combine(uploads, file_guid.ToString()+ ext) ;
                    using (Stream fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyToAsync(fileStream);
                        _film.SubmitGuidFile(file_guid.ToString() + ext, id_film);

                    }
                }
            return View();
        }
        public IActionResult FormFilm(int id)
        {
            return ViewComponent("FormFilm", new { id = id });
        }

        public IActionResult FilmList(string find, int page)
        {
            return ViewComponent("FilmList", new {find = find, page = page-1 });
        }

        public IActionResult Pagination(bool is_searh = true)
        {
            return ViewComponent("Pagination", new { is_searh = is_searh });
        }
        // о
    }
}

FilmsCatalog/Views/Films/DebugForm.cshtml
<script src="~/js/Films.js?version=1"></script>



<div id="divform">
    @await Component.InvokeAsync("FormFilm", new { id = 1 })
</div>

FilmsCatalog/Views/Films/List.cshtml
<script src="~/js/Films.js?version=9"></script>

@{ ViewData["Title"] = "List"; }

<script>
    var count_pages = @(ViewBag.CountPages ?? 0)
</script>
<button type="button" class="btn btn-link" onclick="openDetalies(0);">Добавить</button>

<div class="input-group">
    <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="button" onclick="searh_text();" aria-describedby="basic-addon2">Поиск</button>
    </div>
    <input type="text" id="find_txt" class="form-control" placeholder="Search...">

    <button type="button" class="btn bg-transparent" style="margin-left: -40px; z-index: 100;" onclick="ClearSearh()">
        <i class="fa fa-times"></i>
    </button>
</div>

<div id="table_films">
    @await Component.InvokeAsync("FilmList")
</div>

@{
    Html.RenderPartial("~/Views/Films/ModalCreate.cshtml"); 
}

<div id="pagination_div">
@await Component.InvokeAsync("Pagination")
</div>

FilmsCatalog/Views/Films/ModalCreate.cshtml
<div class="modal fade" id="myModalFilmForm">
    <div class="modal-dialog  modal-dialog-centered" role="document" style="width: 1200px;">
        <div class="modal-content" style="background-color: #EDF3F4;">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                
            </div>
            <h4 class="modal-title">Описание фильма</h4>
            <div class="modal-body" id="FilmFormDiv">

            </div>
        </div>
    </div>
</div>